[package]
name = "wt_ffi"
version = "0.1.0"
authors = ["David Hows <howsdav@gmail.com>", "Peter Schmidt <peter@peterjs.com>"]
build = "build.rs"

[dependencies]
libc = "*"
ansi_term = "*"
bson = "*"
getopts = "*"
